spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  cloud:
    gateway:
      routes:
        - id: smartbank-gateway
          uri: lb://SMARTBANK-GATEWAY
          predicates:
          - Path=/api/smartbank/**
          filters:
          - StripPrefix=2
#    refresh:
#      enabled: false # AOT / Native Image does not support Spring Cloud Refresh Scope